In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import genfromtxt

In [12]:
df = genfromtxt('bank_note_data.txt', delimiter= ',')

In [13]:
print(df)

[[  3.6216    8.6661   -2.8073   -0.44699   0.     ]
 [  4.5459    8.1674   -2.4586   -1.4621    0.     ]
 [  3.866    -2.6383    1.9242    0.10645   0.     ]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771    1.     ]
 [ -3.5637   -8.3827   12.393    -1.2823    1.     ]
 [ -2.5419   -0.65804   2.6842    1.1952    1.     ]]


In [14]:
labels = df[:,4]

In [15]:
# Target Veriables
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [17]:
features = df[:,0:4]

In [18]:
# IV
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [19]:
X = features
y = labels

In [20]:
# Split dataset
from sklearn.model_selection import train_test_split


In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=65)


In [32]:
len(X_test)

1098

In [33]:
len(X_train)

274

In [31]:
len(y_test)

1098

In [34]:
from sklearn.preprocessing import MinMaxScaler

In [36]:
scalar_object =  MinMaxScaler()

In [37]:
scalar_object.fit(X_train)

MinMaxScaler()

In [44]:
scaled_X_train= scalar_object.transform(X_train)

In [45]:
scaled_X_test= scalar_object.transform(X_test)

In [46]:
X_train.max()

17.6772

In [47]:
scaled_X_train.max()

1.0

In [49]:
!pip install Keras

In [51]:
from keras.models import Sequential
from keras.layers import Dense


In [60]:
model = Sequential()
## first hidden layer
model.add(Dense(5, input_dim=4, activation='relu'))

model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

In [56]:
# Compile Model

In [61]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [62]:
model .fit(scaler_X_train, y_train, epochs=10, verbose=2)

Epoch 1/10
9/9 - 1s - loss: 0.7039 - accuracy: 0.3905 - 744ms/epoch - 83ms/step
Epoch 2/10
9/9 - 0s - loss: 0.7002 - accuracy: 0.4088 - 17ms/epoch - 2ms/step
Epoch 3/10
9/9 - 0s - loss: 0.6967 - accuracy: 0.4307 - 17ms/epoch - 2ms/step
Epoch 4/10
9/9 - 0s - loss: 0.6936 - accuracy: 0.4453 - 16ms/epoch - 2ms/step
Epoch 5/10
9/9 - 0s - loss: 0.6908 - accuracy: 0.5547 - 16ms/epoch - 2ms/step
Epoch 6/10
9/9 - 0s - loss: 0.6884 - accuracy: 0.5730 - 16ms/epoch - 2ms/step
Epoch 7/10
9/9 - 0s - loss: 0.6864 - accuracy: 0.5730 - 20ms/epoch - 2ms/step
Epoch 8/10
9/9 - 0s - loss: 0.6846 - accuracy: 0.5730 - 28ms/epoch - 3ms/step
Epoch 9/10
9/9 - 0s - loss: 0.6820 - accuracy: 0.5730 - 16ms/epoch - 2ms/step
Epoch 10/10
9/9 - 0s - loss: 0.6792 - accuracy: 0.5730 - 16ms/epoch - 2ms/step


In [64]:
## Model Evaluation
predictions = model.predict(scaler_X_test)
predicted_classes= np.where(predictions > 0.5, 1, 0)

35/35 [==============================] - 0s 1ms/step


In [65]:
print(predictions)

[[0.48060763]
 [0.47262457]
 [0.47529697]
 ...
 [0.47233066]
 [0.46747035]
 [0.46705088]]


In [67]:
predicted_classes

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [69]:
model.metrics_names

['loss', 'accuracy']

In [71]:
model.evaluate(x=scaler_X_test, y=y_test)

35/35 [==============================] - 1s 5ms/step - loss: 0.6859 - accuracy: 0.5510


[0.6858970522880554, 0.5510018467903137]

In [72]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(y_test, predicted_classes)

array([[605,   0],
       [493,   0]])

In [74]:
print(classification_report(y_test, predicted_classes))

              precision    recall  f1-score   support

         0.0       0.55      1.00      0.71       605
         1.0       0.00      0.00      0.00       493

    accuracy                           0.55      1098
   macro avg       0.28      0.50      0.36      1098
weighted avg       0.30      0.55      0.39      1098



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
